server:
  port: 8081
spring:
  boot:
    message: Hello, department service 
  datasource:
    url: jdbc:mysql://localhost:3306/department-service-db?createDatabaseIfNotExist=true
    username: root
    password: omarSABRI@19982022
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
