server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee-service-db?createDatabaseIfNotExist=true
    username: root
    password: omarSABRI@19982022
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        temp:
          use_jdbc_metadata_defaults: false
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
